const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 199,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Nike Fit Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 999,
      countInStock: 15,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Nike Slim Shoes",
      category: "Shoes",
      image: "/images/p1.jpg",
      price: 65,
      countInStock: 5,
      brand: "Nike",
      rating: 0.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Puma Slim Shoes",
      category: "Shoes",
      image: "/images/p1.jpg",
      price: 115,
      countInStock: 1,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};

export default data;
